### ISSUE TITLE
模型回复带了一些标签内容，请问如何获得纯净内容？

### ISSUE THREAD

**Issue by SH0AN** [THUDM/LongCite#9]

**Comment by Neo-Zhangjiajie** [comment]
你是指<statement><cite>这种吗？去掉就好了，可以使用modeling中的postprocess函数

**Comment by SH0AN** [comment]
> 你是指这种吗？去掉就好了，可以使用modeling中的postprocess函数

请问该函数如何调用，能提供一个例子？

**Comment by Neo-Zhangjiajie** [comment]
可以看modeling.py里的query_longcite函数
